language: generic
dist: xenial
os:
  - linux
  - osx
env:
  global:
    - TARGET_DEVICE="ics"

before_install:
  -  |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
      sudo apt-get update -qq
      sudo apt-get install -qq gcc gperf bison flex texinfo help2man make libncurses5-dev python-dev build-essential
    fi

script:
  - ./build_script.sh

cache:
  directories:
    - ${HOME}/src